services:
  auth:
    container_name: stm-auth
    image: nuwcdivnpt/stig-manager-auth
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - PROXY_ADDRESS_FORWARDING=${PROXY_ADDRESS_FORWARDING}
  db:
    container_name: stm-db
    image: mysql:8.0
    ports:
      - "50001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  api:
    container_name: stm-api
    image: nuwcdivnpt/stig-manager:latest
    environment:
      - STIGMAN_OIDC_PROVIDER=${STIGMAN_OIDC_PROVIDER}
      - STIGMAN_CLASSIFICATION=${STIGMAN_CLASSIFICATION}
      - STIGMAN_DB_HOST=${STIGMAN_DB_HOST}
      - STIGMAN_DB_PASSWORD=${STIGMAN_DB_PASSWORD}
      - STIGMAN_CLIENT_OIDC_PROVIDER=${STIGMAN_CLIENT_OIDC_PROVIDER}
      - STIGMAN_LOG_FORMAT=json
    init: true
    ports:
      - "54000:54000"
